name: Test Notebooks

on: [push, pull_request]

concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: true

jobs:
  test-notebooks:

    if:
      github.event_name == 'push' || github.event.pull_request.head.repo.full_name != github.repository

    name: Test the notebooks
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.11

      - name: Install nox
        run: pip install nox

      - name: Test
        env:
          MPLBACKEND: "Agg"
          OPENTOPOGRAPHY_API_KEY: ${{ secrets.OPENTOPOGRAPHY_API_KEY }}
        run: nox -s test-notebooks --python "3.11"
