name: Test Notebooks

on: [push, pull_request]

jobs:

  test-notebooks:

    if:
      github.event_name == 'push' ||
      github.event.pull_request.head.repo.full_name != github.repository

    name: Test the notebooks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: conda-incubator/setup-miniconda@v3
        with:
          python-version: "3.11"
          miniforge-variant: Miniforge3
          miniforge-version: latest
          auto-update-conda: true

      - name: Install nox
        run: pip install nox

      - name: Test
        env:
          MPLBACKEND: "Agg"
          OPENTOPOGRAPHY_API_KEY: ${{ secrets.OPENTOPOGRAPHY_API_KEY }}
        run: nox -s test-notebooks --python "3.11"
